### ISSUE TITLE
Bug- Substring, Date Read with additional Asterisks Unaccounted For

### ISSUE THREAD

**Issue by bnevets** [SMATechnologies/federal-holidays-to-opcon-calendar-powershell#2]
First, thank you for the script - it was super handy.

Issue List:
It seems the site moved the data to parse for $yearstart and $yearend dates, lines 99,100, didn't have enough time to actually code it to find length and numbers back, just adjusted the hardcode starting indexes:

- `$yearstart = $source[$x].Substring(58,4)`
- `$yearend = $source[$x].Substring(63,4)`

They also have a odd date with three asterisks for inauguration + MLK Jr day (1/20/2025) so code was added to a couple of areas. May not be the best coding, but I also made the dates appear consistent with other days (most show up M/d/yyyy format, so I just used that across the board):
- within the block of
`elseif($date.IndexOf('*') -ge 0)`
I changed the inital if to handle two asterisks to elseif, and added a block of code to handle the three asterisks
`if ($date.IndexOf('***') -ge 0)
                        {$date = [string]($months.IndexOf($date.SubString(0,$date.IndexOf(" ")))+1) + "/" + [string]$date.SubString(($date.IndexOf(" ")+1),($date.Length - ($date.IndexOf(" ")+1))) + "/" + [string]$year + "***" }`
- Under #Add/Subtract dates based on how the holiday falls comment (~Line 129 for me after above change) I changed the initial if to elseif and added this snipped above - probably not necessary, but I was working backwards:
`if($date.Substring($date.Length - 3) -eq "***")
                {
                    $date = $date.Replace('***',"")
                    $date = Get-Date -Date (Get-Date -Date $date) -Format "M/d/yyyy"
                }`

- Also had to update line 109, I believe the initial start index had to be moved back from 8 to 7 `$date = $source[$x].Substring(7,$source[$x].IndexOf("</td>")-($source[$x].IndexOf("<td>")+4))` 

Not the worst of issues, but fixed the red error spam for not liking the sub string and dates with unexpected characters.

**Comment by opconWizard** [comment]
Thanks!  I addressed these in the recent release :)

**Comment by jesnyder13** [comment]
Thank you guys for this script! I noticed that on January 1 2023 there were two asterisks but the script was missing them.  The source looks like this...

		<tr>
			<th scope="row">New Year's Day</th>
			<td>January 1<a href="#20221" id="20221r">*</a>*</td>
			<td>January 1</td>
			<td>January 1</td>
			<td>January 1</td>
			<td>January 1</td>
		</tr>

		<tr>
			<th scope="row">Independence Day</th>
			<td>July 4</td>
			<td>July 4</td>
			<td>July 4</td>
			<td>July 4*</td>
			<td>July 4**</td>
		</tr>

It was finding the ones for July 4th 2027 but not for January 1st 2023.  I believe the <a> tag was messing it up.  I believe I fixed this by replacing the following line.
$getStars = $date.Substring($date.IndexOf('">')+2,2)

With this...
# Match asterisks at end of string
$stars = $date | Select-String -Pattern '\*' -AllMatches
if ($stars) {
  # Extract the asterisks 
  $getStars = $stars.Matches.Value -join ''
}
