### ISSUE TITLE
Missing asterisks due to a tag

### ISSUE THREAD

**Issue by jesnyder13** [SMATechnologies/federal-holidays-to-opcon-calendar-powershell#3]
Thank you guys for this script! I noticed that on January 1 2023 there were two asterisks but the script was missing them. The source looks like this...

	<tr>
		<th scope="row">New Year's Day</th>
		<td>January 1<a href="#20221" id="20221r">*</a>*</td>
		<td>January 1</td>
		<td>January 1</td>
		<td>January 1</td>
		<td>January 1</td>
	</tr>

	<tr>
		<th scope="row">Independence Day</th>
		<td>July 4</td>
		<td>July 4</td>
		<td>July 4</td>
		<td>July 4*</td>
		<td>July 4**</td>
	</tr>
It was finding the ones for July 4th 2027 but not for January 1st 2023. I believe the tag was messing it up. I believe I fixed this by replacing the following line.
```powershell
$getStars = $date.Substring($date.IndexOf('">')+2,2)
```
With this...
```powershell
# Match asterisks at end of string
$stars = $date | Select-String -Pattern '*' -AllMatches
if ($stars) {
  # Extract the asterisks
  $getStars = $stars.Matches.Value -join ''
}
```

**Comment by opconWizard** [comment]
This works well! I shortened it and had to make the pattern an expression but will be adding it to version 1.32, thanks!

$getStars = ($date | Select-String -Pattern '[*]' -AllMatches).Matches.Value -join ''
